---
# file: defaults/main.yml

# ckan user details
ckan_user: {
  name: "ckan",
  system: "yes",
  home_path: "/usr/lib/ckan",
  shell: "/sbin/nologin",
  description: "CKAN User"
}

# latest stable ckan version
ckan_version: "2.3"

# CKAN default site name
ckan_site_name: "ckan.localhost.localdomain"

# CKAN site URL
ckan_site_url: "http://{{ ckan_site_name }}"

# CKAN site title
ckan_site_title: "CKAN"

# CKAN site description
ckan_site_description: "The easy way to get, use and share data"

# CKAN email settings
ckan_email_to: "ckan@yourdomain.com"
ckan_error_email_from: "no-reply@yourdomain.com"
ckan_smtp_server: "smtp.yourdomain.com"
ckan_smtp_starttls: False
ckan_smtp_user: "ckan-mailer"
ckan_smtp_password: "T$UZqA\XeN$}CX8)"
ckan_smtp_mail_from: "no-reply@yourdomain.com"

# disable ckan debugging on production servers unless when
# in dev. mode
ckan_debug_mode: "false"

#default ckan virtualenv path
ckan_virtualenv: "{{ ckan_user.home_path }}/default"

# vim: set sw=2 ts=2:
