---
language: python
python: "2.7"
sudo: required

# environment variables
env:
  - ANSIBLE_INVENTORY=hosts
  - DEFAULT_SOLR_PORT=8983
  - DEFAULT_POSTGRES_PORT=5432

# update indices, install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev python-pip gcc git curl

# update pip & install ansible from pip
install:
  - pip install --upgrade pip
  - pip install ansible

# run tests
script:
  # Run syntax checks
  - "ansible-playbook tests/test.yml -i tests/hosts --connection=local --syntax-check"

  ## Test Solr Installation
  # Test solr role
  - "ansible-playbook tests/solr.yml -i tests/hosts --connection=local"

  # Curl solr web administration page & netcating its port
  - "/usr/bin/curl -I http://localhost:$DEFAULT_SOLR_PORT"
  - "echo | nc -v localhost $DEFAULT_SOLR_PORT"

  ## Test PostgreSQL Installation
  # Test postgresql role
  - "ansible-playbook tests/db.yml -i tests/hosts --connection=local"
  - "echo |nc -v localhost $DEFAULT_POSTGRES_PORT"

# vim: set sw=2 ts=2:
