---
# file: solr.yml

- hosts: solr
  become: yes
  user: provisioning
  vars_files:
    - vars/all.yml
  roles:
    - { role: solr, when: ansible_distribution == "Ubuntu", tags: solr }

# vim: set sw=2 ts=2:
